version: '3'
services:
  structurizr:
    image: structurizr/lite
    container_name: structurizr
    ports:
      - 8080:8080
    environment:
      - STRUCTURIZR_WORKSPACE_PATH=${STRUCTURIZR_WORKSPACE_PATH}
    volumes:
      - ./workspace:/usr/local/structurizr

